'use strict';
(() => {
 const $=id=>document.getElementById(id), $$=s=>[...document.querySelectorAll(s)];
 const missions={
  web:{brief:'Um site para apresentar a chácara. Conecte cada tecnologia à sua função.',roles:[['Estrutura','HTML','HTML organiza o conteúdo da página.'],['Visual','CSS','CSS define o visual e a adaptação às telas.'],['Interação','JavaScript','JavaScript controla os comportamentos da interface.']],pool:['Firebase','CSS','React Native','HTML','MySQL','JavaScript'],project:'web'},
  mobile:{brief:'Um aplicativo com acesso de usuários. Monte esta combinação possível de ferramentas.',roles:[['Interface','React Native','React Native constrói a interface mobile.'],['Autenticação','Firebase Auth','Firebase Authentication gerencia o acesso de usuários.'],['Versionamento','GitHub','GitHub hospeda o histórico do código e facilita colaboração.']],pool:['CSS','GitHub','React Native','MySQL','HTML','Firebase Auth'],project:'mobile'},
  data:{brief:'Organize dados de uma aplicação. Associe cada ferramenta ao papel proposto.',roles:[['Banco relacional','MySQL','MySQL armazena dados em tabelas relacionadas.'],['Consultas','SQL','SQL permite consultar e manipular dados relacionais.'],['Modelagem visual','Workbench','MySQL Workbench auxilia a modelagem e a administração.']],pool:['JavaScript','Workbench','React Native','SQL','HTML','MySQL'],project:'software'}
 };
 let mission='web',selected=null,filled=[false,false,false],completed=new Set();
 function renderLab(){
  const m=missions[mission];$('labBrief').textContent=m.brief;$('stackLab').classList.toggle('lab-complete',filled.every(Boolean));
  $('labSlots').replaceChildren(...m.roles.map(([role,tech],i)=>{const b=document.createElement('button');b.type='button';b.className='lab-slot'+(filled[i]?' filled':'');b.dataset.slot=i;b.setAttribute('aria-label',`${role}: ${filled[i]?tech:'espaço vazio'}`);const small=document.createElement('small');small.textContent=`0${i+1} / ${role}`;const strong=document.createElement('strong');strong.textContent=filled[i]?tech:'+ Conectar';const hint=document.createElement('span');hint.textContent=filled[i]?'Conectado ✓':'Clique ou solte aqui';b.append(small,strong,hint);b.addEventListener('click',()=>{if(selected)place(i);else $('labFeedback').textContent=filled[i]?m.roles[i][2]:'Primeiro escolha uma tecnologia abaixo.';});return b;}));
  $('labPool').replaceChildren(...m.pool.map(tech=>{const b=document.createElement('button');b.type='button';b.className='tech-token';b.textContent=tech;b.dataset.tech=tech;b.setAttribute('aria-pressed',String(selected===tech));if(m.roles.some((r,i)=>filled[i]&&r[1]===tech))b.classList.add('used');b.addEventListener('click',()=>choose(tech));return b;}));
  $('labProject').hidden=!filled.every(Boolean);$('labScore').textContent=`${completed.size} / 3 completos`;
 }
 function choose(tech){selected=tech;$$('.tech-token').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.tech===tech)));$('labFeedback').textContent=`${tech} selecionado. Agora escolha a função no painel.`;}
 function place(index){const m=missions[mission];if(m.roles[index][1]===selected){filled[index]=true;selected=null;if(filled.every(Boolean)){completed.add(mission);$('labFeedback').textContent='Solução conectada! Explore outro desafio ou veja o projeto relacionado.';}else $('labFeedback').textContent=m.roles[index][2];renderLab();$('labSlots').children[index].focus({preventScroll:true});}else{$('labFeedback').textContent=`Nesta combinação, ${m.roles[index][0].toLowerCase()} usa ${m.roles[index][1]}. Tente outra conexão.`;}}
 $$('[data-mission]').forEach(b=>b.addEventListener('click',()=>{mission=b.dataset.mission;selected=null;filled=[false,false,false];$$('[data-mission]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('labFeedback').textContent='Escolha uma tecnologia para começar.';renderLab();}));
 $('labReset').addEventListener('click',()=>{selected=null;filled=[false,false,false];$('labFeedback').textContent='Desafio reiniciado.';renderLab();});
 $('labProject').addEventListener('click',()=>document.querySelector(`.filter[data-filter="${missions[mission].project}"]`).click());
 let tokenDrag=null,ghost=null,suppressClick=false;
 $('labPool').addEventListener('pointerdown',e=>{const button=e.target.closest('[data-tech]');if(!button||e.button!==0||!e.isPrimary)return;tokenDrag={id:e.pointerId,button,tech:button.dataset.tech,x:e.clientX,y:e.clientY,moving:false};button.setPointerCapture(e.pointerId);});
 $('labPool').addEventListener('pointermove',e=>{if(!tokenDrag||e.pointerId!==tokenDrag.id)return;if(!tokenDrag.moving&&Math.hypot(e.clientX-tokenDrag.x,e.clientY-tokenDrag.y)>8){tokenDrag.moving=true;choose(tokenDrag.tech);ghost=document.createElement('div');ghost.className='drag-token-ghost';ghost.textContent=tokenDrag.tech;ghost.setAttribute('aria-hidden','true');document.body.append(ghost);}if(ghost){ghost.style.left=`${e.clientX}px`;ghost.style.top=`${e.clientY}px`;const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]');$$('[data-slot]').forEach(s=>s.classList.toggle('over',s===hit));}});
 function drop(e,canceled=false){if(!tokenDrag||e.pointerId!==tokenDrag.id)return;const wasMoving=tokenDrag.moving;const hit=!canceled&&document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-slot]');const button=tokenDrag.button,id=tokenDrag.id;tokenDrag=null;ghost?.remove();ghost=null;$$('[data-slot]').forEach(s=>s.classList.remove('over'));if(button.hasPointerCapture(id))button.releasePointerCapture(id);if(wasMoving){suppressClick=true;setTimeout(()=>suppressClick=false,0);if(hit)place(Number(hit.dataset.slot));}}
 $('labPool').addEventListener('pointerup',e=>drop(e));$('labPool').addEventListener('pointercancel',e=>drop(e,true));$('labPool').addEventListener('click',e=>{if(suppressClick){e.preventDefault();e.stopImmediatePropagation();}},true);
 renderLab();
 const photos=[['img/cantinho-interior.webp','Sala da chácara Cantinho Projetado JGM'],['img/cantinho-piscina.jpg','Piscina e área verde da chácara Cantinho Projetado JGM']];let photo=0;
 function gallery(delta){photo=(photo+delta+photos.length)%photos.length;$('galleryImage').src=photos[photo][0];$('galleryImage').alt=photos[photo][1];$('galleryCount').textContent=`0${photo+1} / 02`;}
 $('galleryPrev').addEventListener('click',()=>gallery(-1));$('galleryNext').addEventListener('click',()=>gallery(1));let swipe=null;
 $('galleryViewport').addEventListener('pointerdown',e=>{if(e.isPrimary){swipe={id:e.pointerId,x:e.clientX};e.currentTarget.setPointerCapture(e.pointerId);}});$('galleryViewport').addEventListener('pointerup',e=>{if(swipe?.id===e.pointerId){const dx=e.clientX-swipe.x;if(Math.abs(dx)>40)gallery(dx<0?1:-1);swipe=null;}});$('galleryViewport').addEventListener('pointercancel',()=>swipe=null);
 const flow=[['Uma interface.\nUm ponto de partida.','React Native organiza a interface com que a pessoa interage no aplicativo.'],['Quem pode\nentrar?','Firebase Authentication gerencia o login. Autenticar identifica o usuário; regras de acesso determinam o que ele pode fazer.'],['Dados conectados.\nRegras definidas.','A aplicação consulta e atualiza dados no Firebase. Regras de segurança precisam limitar o acesso conforme o usuário.']];
 $$('[data-flow]').forEach(b=>b.addEventListener('click',()=>{const [title,copy]=flow[Number(b.dataset.flow)];$('flowTitle').textContent=title;$('flowCopy').textContent=copy;$$('[data-flow]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));
 const answers={minus:['a - b',2,'Subtração: 5 menos 3 resulta em 2.'],plus:['a + b',8,'Bug resolvido! O operador + soma os valores: 5 + 3 = 8.'],times:['a * b',15,'Multiplicação: 5 vezes 3 resulta em 15.']};
 $$('[data-answer]').forEach(b=>b.addEventListener('click',()=>{const [expression,result,explanation]=answers[b.dataset.answer];$('codeExpression').textContent=expression;$('codeResult').textContent=`Saída: ${result}. ${explanation}`;$$('[data-answer]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));}));
 const drafts={opportunity:'Olá, Jonas! Gostaria de conversar sobre uma oportunidade em tecnologia.',project:'Olá, Jonas! Tenho uma ideia de projeto e gostaria de conversar com você.',connection:'Olá, Jonas! Vi seu portfólio e gostaria de trocar ideias sobre tecnologia.'};
 $('contactTopic').addEventListener('change',()=>{const draft=drafts[$('contactTopic').value];$('contactDraft').textContent=draft;$('contactWhatsApp').href=`https://wa.me/5511958789371?text=${encodeURIComponent(draft)}`;});
})();

